### ISSUE TITLE
QGis crashes just after building geometry

### ISSUE THREAD

**Issue by TheBeachLab** [jawensi/DEMto3D-QGIS-Plugin#11]
Hi Francisco Javier, congratulations on this great plugin. I have been looking for an open source solution like this a long ago. I have a problem with the plugin, I don't know if it is a local issue or a bug or a dataset problem. The thing is that I cannot get a log screen to debug the error. 

QGis crashes right after building geometry. When It reaches 100% then it says building STL file and it suddenly crashes. So I guess the problem lays in the building STL step.

Do you happen to have a image set that you know it is working so that I can discard that this is not a dataset problem?

```
System info:
Linux Manjaro (Arch based)
DEMto3D Plugin version 2.3.3
QGIS version
2.14.0-Essen
QGIS code revision
exported
Compiled against Qt
4.8.7
Running against Qt
4.8.7
Compiled against GDAL/OGR
2.0.2
Running against GDAL/OGR
2.0.2
Compiled against GEOS
3.5.0-CAPI-1.9.0
Running against GEOS
3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version
9.5.1
SpatiaLite Version
4.3.0a
QWT Version
6.1.2
PROJ.4 Version
492
QScintilla2 Version
2.9.1
```

Francisco

**Comment by jawensi** [comment]
Hello, thanks for the congratulations. DEMto3D was developped on QGIS 2.12 so I have to check the stability of the plugin on QGIS 2.14.  Regards

**Comment by kokkytos** [comment]
I also have the same problem under QGIS 2.12 and Arch Linux 64bit. It crashes...
Some info about my qgis:

QGIS version
2.12.1-Lyon

QGIS code revision
exported

Compiled against Qt
4.8.7

Running against Qt
4.8.7

Compiled against GDAL/OGR
2.0.1

Running against GDAL/OGR
2.0.2

Compiled against GEOS
3.5.0-CAPI-1.9.0

Running against GEOS
3.5.0-CAPI-1.9.0 r4084

PostgreSQL Client Version
9.4.5

SpatiaLite Version
4.3.0a

QWT Version
6.1.2

PROJ.4 Version
491

QScintilla2 Version
2.9

**Comment by kokkytos** [comment]
It is a multi-thread issue...
I commented out that lines in **_Export_dialog.py_** and it worked (except the progressbar):
`self.Model.updateProgress.connect(lambda: self.ui.progressBar.setValue(self.ui.progressBar.value() + 1))`
`self.STL.updateProgress.connect(lambda: self.ui.progressBar.setValue(self.ui.progressBar.value() + 1))`

**Comment by jawensi** [comment]
Thank you for your comment, the multi-thread task gave me quite a few problems. I will think how to fix it.

**Comment by TheBeachLab** [comment]
@kokkytos how did you debug the problem?

**Comment by kokkytos** [comment]
I didn't debug it. From my experience...Sometime I wrote a multithreading qgis plugin and I also had the same crashes due to problematic threating code. So I just commented out the slot part of code...
Flat STL, please set qgis project CRS the same as the input geotiff and try again.

**Comment by jeremybmerrill** [comment]
I also had this problem where QGIS crashes while building the STL model (on Ubuntu, QGIS 2.14 Essen.) Luckily, @kokkytos's solution worked for me; after modifying `Export_dialog.py`, I was able to successfully build the STL.

In greater depth, I edited the file at `~/.qgis2/python/plugins/DEMto3D/DEMto3D_Dialog/Export_dialog.py` to add a `#` at the start of lines 48 and 60, which are the two lines beginning `self.Model.updateProgress`.
