### ISSUE TITLE
No data values

### ISSUE THREAD

**Issue by danielkschneider** [jawensi/DEMto3D-QGIS-Plugin#13]
Hi, it would be great if you could do something with no data values, e.g. ask the user to either ignore them or to substitute a no data value with another value or interpolate to neighbors.

Of course, people with reading skills can figure out a solution. I described a solution for large ground level missing data here:
https://edutechwiki.unige.ch/en/3D_printing_of_digital_elevation_models#Dealing_with_no_data_values_.28missing_data.29

So this is just a feature request for a future version, not a bug :)

**Comment by jawensi** [comment]
No data values are converted to minimun model height.
