### ISSUE TITLE
QGIS3 Conversion

### ISSUE THREAD

**Issue by r-barnes** [jawensi/DEMto3D-QGIS-Plugin#14]
I have a branch started at "https://github.com/r-barnes/DEMto3D-QGIS-Plugin/tree/qgis3" to convert the plugin to QGIS3.

**Comment by gromain** [comment]
Hey!

I'm interested in this conversion, how is it going?

**Comment by r-barnes** [comment]
It turns out that I don't know how to work with QGIS well and don't have a lot of time to learn.

However... I was motivated to build a Python script that converts a GDAL accessible input and turns it into an STL: https://github.com/r-barnes/DEMto3D

The README needs updating. But if you run `./dem_to_stl.py` the help in that script is up to date. Please open an issue on that repo if you have questions!
