### ISSUE TITLE
error in model height  

### ISSUE THREAD

**Issue by fabricix** [jawensi/DEMto3D-QGIS-Plugin#15]
I'm trying to export an DEM file to SLT.
The DEM model have the followings diementions aprox. (dX=4500,dy=6580,dz=1651).
When I'am trying to export to SLT with DEMto3D in QGIS2.18.20, the model height is in maximum 2.3mm, and never a can have the real proportion ins distentions. Why?
<a href="https://imgur.com/gcQsHjN"><img src="https://i.imgur.com/gcQsHjN.png" title="source: imgur.com" /></a>

**Comment by jawensi** [comment]
You have to set correctly the data CRS (Coordinate Reference System). As you can see you have set a geographical CRS and the values of the raster extension are biger than 180 degrees in longitude and 90 degrees in latitude.
