### ISSUE TITLE
Exports empty file, no error (QGIS 3.6, Windows)

### ISSUE THREAD

**Issue by dsconstable** [jawensi/DEMto3D-QGIS-Plugin#16]
Plugin exports empty file (0 KB) upon running. Input file is positive integer DEM and no errors identified in parameters.  When I click export the plugin reports that the file has been created in less than one second, but the file itself if 0 KB and cannot be opened. Has anyone else run into this issue?

Version: Plugin v3.1, QGIS 3.6, Windows 10 64 bit.

**Comment by mwenesi** [comment]
I have had the same issue. Three times I get empty file (0 KB) then suddenly one file works. Then it reverts for the 5th and 6th attempt

**Comment by jawensi** [comment]
fixed. There was an exception in the bilineal interpolation that don't return any value.
