### ISSUE TITLE
QGIS 3.10 Linux - DemTo3D doesn't work

### ISSUE THREAD

**Issue by Omar-Ruelas** [jawensi/DEMto3D-QGIS-Plugin#18]
I have a DTM in format .TIF when i tray to open show up a windows that say: 
There is none layer upload and visible

**Comment by nesnejretep** [comment]
I experience a similar issue with QGIS 3.10.1 A Coruña on Linux Mint: "No visible raster layer loaded", despite having a geotiff loaded and selected.

**Comment by nios24** [comment]
Had the same issue with QGIS 3.10 and DEMto3D  "No visible raster layer loaded". Here is my solution. I'm not sure if this is the correct way but it seems to be a python related problem.
I'm running QGIS on Ubuntu 18.04 and the plugin DEMto3D.py is located in:
~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DEMto3D
For other OS search for the file DEMto3D.py
In line 111 is compared to a integer "layer.type() == 1" but variable layer is now of type "enum"
line 111: if layer.type() == 1 and QgsProject.instance().layerTreeRoot().findLayer(layer).isVisible():
I just replaced "layer.type() == 1" by "layer.RasterLayer" so line 111 should look like:
              if layer.RasterLayer and QgsProject.instance().layerTreeRoot().findLayer(layer).isVisible():
Now save the file and start qgis again and it should work.
Not sure if this is just a dirty workaround.

**Comment by jawensi** [comment]
I change the comparation with de "enum" type data.
