### ISSUE TITLE
Error Import Failed in Vcarve from QGIS 3.10.2

### ISSUE THREAD

**Issue by jamin35008** [jawensi/DEMto3D-QGIS-Plugin#19]
I'm trying to convert a tiff to stl using DEMto3d in QGIS v3.10.2 and everytime I try to open the stl in vcarve I get the "Error Import Failed"  

I looked at the file in its folder and noticed that the file size is 1KB.

In QGIS everything looks to to process and I even get a message saying "stl created"

Using windows 7 64bit.

Has this been a issue in the latest QGIS version?  I know someone who is using 3.10.1 with no issues.

**Comment by jawensi** [comment]
Be sure that the CRS (Coordinate Reference System) of the data is the correct CRS. Users build empty models when the CRS of the data was setting wrong.
If you continue having problems, you can send me the DEM file to have a look and try to discover what has gone wrong.

**Comment by geograz** [comment]
Hello jawensi. I am also experiencing this problem and I am quite sure that it is related to the CRS as you say. The rasterfile which I'd like to 3D print is actually a random fractal surface that I created and converted to a rasterfile in cartesian coordinates, so there is no "primary" CRS. Can you suggest which CRS I should use to make it work?

PS: I have used your plugin several times for other "real" DEMs and there it works great!

**Comment by jawensi** [comment]
If you have not any CRS assigned to your data, I recommend you to assign a CRS with units in meters. Thereby there will be no CRS transformation as DEMto3D transform the data units to meters to after convert to milimeters (final model units).

**Comment by jamin35008** [comment]
Thank you jawensi!  The CRS was the issue for me.  I was using the incorrect value.  Everything works perfectly now.
