### ISSUE TITLE
The plugin hangs QGIS

### ISSUE THREAD

**Issue by pcav** [jawensi/DEMto3D-QGIS-Plugin#2]
The plugin brings QGIS at 100% CPU for a very long time, without messages to the user.

**Comment by jawensi** [comment]
The pluging communicates with the user, when is building a model, through a dialog that shows a progress bar and a label.

**Comment by pcav** [comment]
Yes, I noticed this, but the bar does not move (what is the expected time for a 4kcells raster?)

**Comment by jawensi** [comment]
The building expected time depends on the size of the model and the spacing, not the raster loaded. 

The dimensions are input in millimeters, width, high or scale of the final model. Entering a value and pressing “INTRO”, the other two are automatically calculated.

The bigger is the spacing the more generalized will be the model and less time take build it. 
For example a 100 x 100 mm model size, with a spacing of 1 mm, will be form in about 20 sec. DEMto3D calculate the height of the 10000 points (100x100) and then write the surface in STL format.

**Comment by pcav** [comment]
Oh, right. Perhaps better adding a warning when the expected computation time is too long?

**Comment by pcav** [comment]
BTW, the saved file contains only:

solid model
endsolid model

**Comment by jawensi** [comment]
Could you tell me with parameters you use to define the model (width, height, scale, spacing and base height)?

**Comment by pcav** [comment]
This may be triggered by the error reported in #7

**Comment by pcav** [comment]
1554747.231 4924820.77 1653585.747 4827938.57
2 100 100 1000000
height 1

**Comment by jawensi** [comment]
Entering a value of width, high or scale and pressing “INTRO”, the other two are automatically calculated. I tried your data and entering 100 mm height and pressing 'INTRO' width and scale are little diferents to 100 and 1000000
(Of course the SCR layer must be correct)

**Comment by pcav** [comment]
Where is "INTRO"?

**Comment by jawensi** [comment]
Intro key

**Comment by pcav** [comment]
OK, Enter. Now the scale param is different, but I only get in the file:

solid model

**Comment by amefad** [comment]
Me too i'm experiencing the same problem..

Qgis 2.8.3 in windows and Linux

Maybe the input raster has to be geographic

**Comment by jawensi** [comment]
In the last version I change the input value way. Now the values are filling automatically when input a value, no need 'enter' keyboard button. 

Regarding empty model I experience that situation when I choose the wrong SCR. Be aware to define the correct SCR. DEMto3D works with goegraphic and projected coordinates.
