### ISSUE TITLE
is DEMto3D only for raster files?

### ISSUE THREAD

**Issue by theo258** [jawensi/DEMto3D-QGIS-Plugin#22]
Am I correct that this plugin can only convert raster data to STL files? When using QGIS I loaded a shapefile and my intension was to convert this shapefile to a STL file, but it is not a raster file. If the above is the case, I kindly recommend adding this to the description of the plugin. In case someone is interested I added my shapefiles here.
[my-shapefile.zip](https://github.com/jawensi/DEMto3D-QGIS-Plugin/files/4430867/my-shapefile.zip)
![raster-error](https://user-images.githubusercontent.com/60721219/78420618-8a929e00-7605-11ea-9cf4-5a2eefb5df0c.jpg)

**Comment by jawensi** [comment]
That´s right, DEMto3D only convert raster files, it is the reason because the plugin is in the raster menu. Anyway I will update the description to be more clear.
The treatment of vector files is in the roadmap.
