### ISSUE TITLE
Units can be incorrectly detected, causing the program to only output flat rectangles

### ISSUE THREAD

**Issue by furrysalamander** [jawensi/DEMto3D-QGIS-Plugin#26]
After tearing my hair out for many hours today, I was able to figure out why the plugin was only outputting flat rectangles.  It turns out that something about my raster or how I was loading it caused DEMto3D to think that the units for my file were in degrees.  The math that DEMto3D uses for files that are in degrees is radically different from the math for meters, causing it to calculate a negative scale among many other problems.  I was able to get my DEM through the program by simply replacing line 94 of `DEMto3D_dialog.py` with
```
self.units = 0
```
https://github.com/jawensi/DEMto3D-QGIS-Plugin/blob/365b688229014a88bac3ccf4af9a8e89c450446e/DEMto3D_Dialog/DEMto3D_dialog.py#L94

Obviously, this solution breaks compatibility with files that are in degrees, but I am not the only one in the last week who has experienced this issue.  Several users on Reddit reported the same symptoms here:

https://www.reddit.com/r/3Dprinting/comments/l0nnsa/printed_a_7_mile2_section_of_chicago_using_lidar/gjvqdf2?utm_source=share&utm_medium=web2x&context=3

Which is what helped me realize I was not alone.

**Comment by furrysalamander** [comment]
This seem to occur whenever you're trying to convert a raster that doesn't have a CRS defined.  Could we maybe get a simple toggle to force it to use meters whenever this is the case?

**Comment by jawensi** [comment]
When you open a file in QGIS which doesn't have a defined CRS, QGIS assign it the CRS of the project canvas. When the data units are in meters and the CRS units are in degrees and vice versa, there is a problem not only with DEMto3D all the processes that manage these data will return an incorrect answer. 
I recommend you to set a correct CRS to your data and then use it in DEMto3D.
