### ISSUE TITLE
Scale doesn't auto-enter - plugin refuses to work

### ISSUE THREAD

**Issue by koalakoalabanana** [jawensi/DEMto3D-QGIS-Plugin#29]
I was trying to print a world DEM (ETOPO1 ice sheet cell version) and when I entered the desired width (100mm) the scale field didn't auto-fill itself.
- I manually defined the CRS based on ETOPO1's metadata
- I selected the correct layer
- I selected the entire layer
- The DEM was in **degrees**
DEMTo3D refuses to work if the scale field is incorrectly filled. Manually defining the scale did not work either.

**Comment by jawensi** [comment]
Could you send me the DEM file and the CRS used?

**Comment by koalakoalabanana** [comment]
ETOPO1_Ice_c_geotiff.tif
<https://drive.google.com/file/d/1fQ-qrEMww9G2WLEHw68rXgp9JX49tz74/view?usp=drive_web>
It's ~450 MB so it's quite big. CRS was WGS 84 geographic which I got from
the same place I got the DEM from (
https://ngdc.noaa.gov/mgg/global/global.html)

**Comment by jawensi** [comment]
There was a precission bug. It's fixed in the new versión 3.5
