### ISSUE TITLE
STL export a rectangle

### ISSUE THREAD

**Issue by yceballost** [jawensi/DEMto3D-QGIS-Plugin#30]
Hi!

I'm trying to use this plugin with QGIS but when I use it, a rectangle is exported in .stl.

![image](https://user-images.githubusercontent.com/6722153/149558147-9fa8ba92-1ee1-4178-bd01-0f29b5990f3f.png)

1. I import .asc file in QGIS
2. Open DEMto3D
	
![image](https://user-images.githubusercontent.com/6722153/149558270-31d88d81-c9d8-4a72-a366-3d67bd1cee64.png)

Any help? 

Thanks in advance! And thanks for the plugin!

**Comment by AndySwiss** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/97861211/149688913-2cb5c81d-3d21-4ad6-866c-6cd502dfda0c.png)
![image](https://user-images.githubusercontent.com/97861211/149689077-7a5cf381-2b01-44ff-a47b-9cb7f35afa9a.png)
`General
Name	Bel4
Path	C:\Bel\Bel4.tif
Sidecar file	Bel4.tfw
Total size	2.20 GB
Last modified	lunedì, 17 gennaio 2022 02:37:28 (Bel4.tfw)
Provider	gdal


Information from provider
Extent	2721999.9899999997578561,1116000.0000000000000000 : 2723000.0099999997764826,1117000.0200000000186265
Width	33334
Height	33334
Data type	Float32 - Thirty two bit floating point
GDAL Driver Description	GTiff
GDAL Driver Metadata	GeoTIFF
Dataset Description	C:\Bel\Bel4.tif
Compression	LZW
Band 1	
STATISTICS_APPROXIMATE=YES
STATISTICS_MAXIMUM=480.14999389648
STATISTICS_MEAN=290.77781378413
STATISTICS_MINIMUM=222.44999694824
STATISTICS_STDDEV=62.555380775828
STATISTICS_VALID_PERCENT=99.88
More information	
TIFFTAG_ARTIST=created by LAStools (c) martin.isenburg@rapidlasso.com
TIFFTAG_SOFTWARE=LAStools is a product of rapidlasso GmbH, Germany
Dimensions	X: 33334 Y: 33334 Bands: 1
Origin	2.722e+06,1.117e+06
Pixel Size	0.02999999999999999889,-0.02999999999999999889


Coordinate Reference System (CRS)
Unknown


Identification
Identifier	
Parent Identifier	
Title	
Type	
Language	
Abstract	
Categories	
Keywords	


Extent
CRS	
Spatial Extent	CRS: - Projected
X Minimum: 0
Y Minimum: 0
X Maximum: 0
Y Maximum: 0
Temporal Extent	Start: 
End:


Access
Fees	
Licenses	
Rights	
Constraints	




Bands
Band count	1

Number	Band	No-Data	Min	Max
1	Band 1	-9999	222.4499969482	480.1499938965
`

**Comment by jawensi** [comment]
Be sure that the CRS (Coordinate Reference System) of the DEM data is the correct CRS. Some users have problems
when the CRS of the data was incorrect or is unknown.

**Comment by jawensi** [comment]
Another reason could be that the area to export is to big, and the scale very small. In that case you have to increase the vertical exaggeration to notice relief. I tried to make a model with data from https://touchterrain.geol.iastate.edu/ and I didn't have problems.

**Comment by marclura** [comment]
Hi! I'm having the same problem, no matter the terrain the "Model height" automatically calculated stays always at 2mm. I'm working on a newer mac version (macOS Monterey 12.1). On an older version of the OS the plugin works flawlessly. Maybe it's a newer python version that does that? Currently the 3.9.5.
