### ISSUE TITLE
Base of STL slightly larger than top layer

### ISSUE THREAD

**Issue by cdepeuter** [jawensi/DEMto3D-QGIS-Plugin#31]
I am using this plugin to produce layers with a non-standard boundary cropped by vector masks (e.g. country borders). the rectangular base layer of no height can be easily deleted, but the angle face going from the base to the top is not exactly vertical, making it impossible to piece multiple stls together with a continuous top. See screenshot where the distance between the base and the cube is smaller than at the top. I would like this distance to be constant. Can you point to where i can make a change in the code in a fork to make the side faces strictly vertical? 

![Screenshot from 2022-10-05 19-08-41](https://user-images.githubusercontent.com/1150959/194199181-d874b4c8-fd48-43cf-bafb-dae182693225.png)

**Comment by jawensi** [comment]
The mesh built by DEMto3D follow a rectangular pattern. So only the walls has vertical faces. Inside the mesh all the points has diferent x, y coordinates. To get vertical face inside the model you should modify the mesh builder that is in the file Model_Builder.py. 
But I recommend you to edit the STL with booleans operation in Blender. You should get the geometries to cropp the elevation model first. I think you can do in Blender from svg file with the boundary geometry and then extrude it.

**Comment by cdepeuter** [comment]
i will attempt this thank you
