### ISSUE TITLE
[Feature request] Do not export rectangular pedestal

### ISSUE THREAD

**Issue by kubark42** [jawensi/DEMto3D-QGIS-Plugin#34]
### Request
Give option not to export rectangular pedestal.

### Description
When I export, I invariably get a pedestal around non-rectangular parts: 
<img width="915" alt="Screen Shot 2022-12-22 at 10 59 44 AM" src="https://user-images.githubusercontent.com/1118185/209173578-29a6de53-503a-4e13-a14f-8bed2a1860ff.png">

I wish to print without this excess material. I have tried making the `base height` be negative, but all this does is remove material inside the extents, but still leaves a very thin pedestal layer:

<img width="596" alt="Screen Shot 2022-12-22 at 11 04 01 AM" src="https://user-images.githubusercontent.com/1118185/209174381-a3988953-117d-4617-ae8a-5010bc4af2c7.png">

Ideally, this would result in the following STL:
<img width="807" alt="Screen Shot 2022-12-22 at 11 05 23 AM" src="https://user-images.githubusercontent.com/1118185/209174610-f68ce5f4-0cee-440e-aebe-37f3ac9e5c94.png">

**Comment by kubark42** [comment]
I've been poking around at the code, but my python isn't very advanced and there aren't many comments which describe what I think I'm looking for. However, it looks like it might be in this area: https://github.com/jawensi/DEMto3D-QGIS-Plugin/blob/2ab70aff555a764981a87df7834bb59e8c942d69/model_builder/Model_Builder.py#L324

**Comment by jawensi** [comment]
Currently it is not possible to cut the model in a specific height, resulting in a contour cut. DEMto3D only works with rectangular models since it works with raster data, not vector. It is a good feature that I would like to develop in the future.
To cut the model I recommend you to use the software 3d Builder. It is easy to use.
