### ISSUE TITLE
Please provide sensible defaults

### ISSUE THREAD

**Issue by pcav** [jawensi/DEMto3D-QGIS-Plugin#4]
To help first usage of the plugin

**Comment by jawensi** [comment]
Are you referring a default inicial parameters (height, width, spacing...)?.

**Comment by pcav** [comment]
Exactly

**Comment by jawensi** [comment]
Each raster layer has diferent resolution, extent and height range, and each model has diferent size which are relating to the first. So it is dificult to set default parameters.
